### ISSUE TITLE
NoClassDefFoundError: okhttp3/MediaType, after upgrading to 0.16.0

### ISSUE THREAD

**Issue by larskristianhaga** [meilisearch/meilisearch-java#893]
**Description**
After upgrading to version `0.16.0` the application crashes at startup with a exception `Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/MediaType`.

Full stacktrace:
```Java
Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/MediaType
	at com.meilisearch.sdk.http.CustomOkHttpClient.<clinit>(CustomOkHttpClient.java:19)
	at com.meilisearch.sdk.HttpClient.<init>(HttpClient.java:31)
	at com.meilisearch.sdk.Config.<init>(Config.java:77)
	at com.meilisearch.sdk.Config.<init>(Config.java:39)
	at no.cappelendamm.meilisearchokhttpdemo.MeilisearchOkhttpMediaTypeApplication.main(MeilisearchOkhttpMediaTypeApplication.java:25)
Caused by: java.lang.ClassNotFoundException: okhttp3.MediaType
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 5 more
```

**Expected behavior**
Application not crashing due to a `NoClassDefFoundError`.

**Current behavior**
Application crashing due to a `NoClassDefFoundError`.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: [macOS, 15.6.1 (24G90)]
- meilisearch-java version: [0.16.0]

Demo - https://github.com/larskristianhaga/Meilisearch-OKHTTP-MediaType-demo

**Comment by larskristianhaga** [comment]
> Hi there! What is your java version? Because it seems we remove compatibility to Java 8 in the latest version 👀

21, using Temurin JDK

**Comment by zhuyisuzhi** [comment]
From 0.17.1 onwards the okhttp version was changed to 5.x again and the same issue NoClassDefFoundError came up again, so I had to manually exclude okhttp and import the 4.x version of okhttp

>         
        <dependency>
            <groupId>com.meilisearch.sdk</groupId>
            <artifactId>meilisearch-java</artifactId>
            <version>0.18.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.12.0</version>
        </dependency>

>
